language: go
go:
    - 1.6.2
env:
    global:
        - GO15VENDOREXPERIMENT=1
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - go test ./arrimpl -v -covermode=count -coverprofile=coverage.out
    - "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
